### ISSUE TITLE
Fix ConcurrentModificationException/IOOBE in GamePane.paintAll()

### ISSUE THREAD

**Issue by williewheeler** [williewheeler/air-rage#19]
~~~
	private <T extends GameObject> void paintAll(Graphics g, List<T> gameObjects, Renderer renderer) {

		// FIXME This is generating a ConcurrentModificationException.
		// Somewhere we are trying to remove a game object while we're iterating over this list. (Note that the "for"
		// shorthand uses iteration behind the scenes.)
		// http://stackoverflow.com/questions/17067626/java-arraylist-and-exception-in-thread-awt-eventqueue-0-java-util-concurrentm
		//
		// Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
		// at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
		// at java.util.LinkedList$ListItr.next(LinkedList.java:888)
		// at com.williewheeler.airrage.ui.GamePane.paintPlayerMissiles(GamePane.java:118)
		// at com.williewheeler.airrage.ui.GamePane.paint(GamePane.java:50)
		// at javax.swing.JComponent.paintChildren(JComponent.java:889)
		// at javax.swing.JComponent.paint(JComponent.java:1065)
		// at javax.swing.JComponent.paintChildren(JComponent.java:889)
		// at javax.swing.JComponent.paint(JComponent.java:1065)
//		for (T gameObject : gameObjects) {
//			paint(g, gameObject, renderer);
//		}

		// I'm expecting this to give an IndexOutOfBoundsException every now and then, given the above.
		// Yup. See below. So somehow I'm modifying the list of game objects during a repaint().
		//
		// Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
		// at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
		// at java.util.LinkedList.get(LinkedList.java:476)
		// at com.williewheeler.airrage.ui.GamePane.paintAll(GamePane.java:164)
		// at com.williewheeler.airrage.ui.GamePane.paint(GamePane.java:82)
		// at javax.swing.JComponent.paintChildren(JComponent.java:889)
		// at javax.swing.JComponent.paint(JComponent.java:1065)
		// at javax.swing.JComponent.paintChildren(JComponent.java:889)
		// at javax.swing.JComponent.paint(JComponent.java:1065)
		// at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
		int n = gameObjects.size();
		for (int i = 0; i < n; i++) {
			paint(g, gameObjects.get(i), renderer);
		}
	}
~~~

**Comment by williewheeler** [comment]
The problem is that there are two separate threads working on the same list: main and AWT-EventQueue-0. The main thread is calling CollisionDetector methods and hence updating the list. Meanwhile AWT-EventQueue-0 is painting.

~~~
		// 2016-10-16 16:38:22 TRACE GamePane:181 - AWT-EventQueue-0, entity=com.williewheeler.airrage.model.entity.PuffOfSmoke@39c3587b
		// 2016-10-16 16:38:22 TRACE GamePane:181 - AWT-EventQueue-0, entity=com.williewheeler.airrage.model.entity.PuffOfSmoke@7fc2d567
		// 2016-10-16 16:38:22 TRACE GamePane:181 - AWT-EventQueue-0, entity=com.williewheeler.airrage.model.entity.PuffOfSmoke@4486b7e1
		// 2016-10-16 16:38:22 TRACE GamePane:181 - AWT-EventQueue-0, entity=com.williewheeler.airrage.model.entity.PuffOfSmoke@27d78f8e
		// 2016-10-16 16:38:22 TRACE CollisionDetector:37 - main, missile=com.williewheeler.airrage.model.entity.EnemyMissile@1c2c22f3
		// 2016-10-16 16:38:22 TRACE CollisionDetector:37 - main, missile=com.williewheeler.airrage.model.entity.EnemyMissile@18e8568
		// Exception in thread "AWT-EventQueue-0" 2016-10-16 16:38:22 TRACE CollisionDetector:37 - main, missile=com.williewheeler.airrage.model.entity.EnemyMissile@33e5ccce
		//   java.util.ConcurrentModificationException
		// 2016-10-16 16:38:22 TRACE CollisionDetector:37 - main, missile=com.williewheeler.airrage.model.entity.EnemyMissile@5a42bbf4
		// 2016-10-16 16:38:22 TRACE CollisionDetector:37 - main, missile=com.williewheeler.airrage.model.entity.EnemyMissile@270421f5
		//   at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
~~~

**Comment by williewheeler** [comment]
See http://stackoverflow.com/questions/7156949/main-thread-vs-ui-thread-in-java
